version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t aws-developer-tools .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push aws-developer-tools
